import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve
import os

# 1. Define the experimental grid
versions = {
    "V1": "V1 (CNN Baseline)",
    "V2": "V2 (Deep ResNet)",
    "V3": "V3 (XLS-R Transformer)",
    "V4": "V4 (RawNet2 SincNet)",
    "V5": "V5 (Orthogonal Fusion)"
}

train_envs = ["FoR", "ASVspoof5"]
test_envs = ["FoR", "ASVspoof5"]

export_dir = "Paper1_Data_Exports"
heatmap_data = []

print("🔍 Scanning Data Exports and Calculating EERs...")

# 2. Iterate through all 20 possible combinations
for v_key, v_name in versions.items():
    row_data = {"Architecture": v_name}
    for train_env in train_envs:
        for test_env in test_envs:
            # Clean up the names for the plot labels
            col_name = f"Train {train_env.replace('ASVspoof5', 'ASVspoof')}\nTest {test_env.replace('ASVspoof5', 'ASVspoof')}"
            
            # Predict the exact filename generated by your main.py scripts
            csv_filename = f"raw_scores_{v_key}_Train{train_env}_Test{test_env}.csv"
            csv_path = os.path.join(export_dir, csv_filename)
            
            if os.path.exists(csv_path):
                # 3. Calculate EER directly from raw scores
                df = pd.read_csv(csv_path)
                labels = df['True_Label'].values
                scores = df['Predicted_Score'].values
                
                if len(np.unique(labels)) > 1: # Ensure we have both spoofs and bonafides
                    fpr, tpr, thresholds = roc_curve(labels, scores, pos_label=1)
                    fnr = 1 - tpr
                    idx = np.nanargmin(np.absolute((fpr - fnr)))
                    eer = fpr[idx] * 100 # Convert to Percentage
                    row_data[col_name] = eer
                    print(f"✅ Found {csv_filename} -> Computed EER: {eer:.2f}%")
                else:
                    row_data[col_name] = np.nan
            else:
                row_data[col_name] = np.nan # CSV not generated yet
                
    heatmap_data.append(row_data)

# 4. Construct the Dataframe
df_heat = pd.DataFrame(heatmap_data).set_index("Architecture")

# Reorder columns to group In-Domain vs Out-of-Domain logically
column_order = [
    "Train FoR\nTest FoR", 
    "Train ASVspoof\nTest ASVspoof", 
    "Train FoR\nTest ASVspoof", 
    "Train ASVspoof\nTest FoR"
]
df_heat = df_heat[column_order]

# 5. Render the High-Resolution Publication Figure
plt.style.use('seaborn-v0_8-paper')
fig, ax = plt.subplots(figsize=(10, 6.5))

# Plot Heatmap (Missing CSVs will be rendered as blank/grey squares)
sns.heatmap(df_heat, annot=True, fmt=".2f", cmap="YlOrRd", 
            cbar_kws={'label': 'Equal Error Rate (EER %)'},
            linewidths=1.5, linecolor='white',
            annot_kws={"size": 12, "weight": "bold"},
            ax=ax, vmin=0, vmax=70, mask=df_heat.isnull())

ax.set_title("Comprehensive Cross-Corpus Generalization Matrix (EER %)", 
             fontsize=14, fontweight='bold', pad=20)
ax.set_ylabel("System Topology", fontsize=12, fontweight='bold')
ax.set_xlabel("Evaluation Paradigm", fontsize=12, fontweight='bold')
ax.xaxis.tick_top()
ax.xaxis.set_label_position('top')

plt.tight_layout()
output_filename = "Paper1_Complete_Matrix_Heatmap.pdf"
plt.savefig(output_filename, format='pdf', dpi=300, bbox_inches='tight')
print(f"\n📊 Master Heatmap successfully saved to '{output_filename}'")
plt.show()